module.exports = {
    additionsSchema:  require("./addition.schema"),
    additionOptionsSchema:  require("./additionOptions.schema"),
    addresseSchema:  require("./addresse.schema"),
    AdvertisementSchema:  require("./advertisement.schema"),
    AppSchema:  require("./app.schema"),
    BranchSchema:  require("./branch.schema"),
    categorieSchema:  require("./category.schema"),
    couponSchema:  require("./coupon.schema"),
    notesSchema:  require("./notes.schema"),
    orderSchema:  require("./order.schema"),
    otpSchema:  require("./otp.schema"),
    PolygonSchema:  require("./polygon.schema"),
    productSchema:   require("./product.schema"),
    productSizeSchema:   require("./product.size.schema"),
    userSchema:  require("./user.schema"),
    pointSchema:  require("./point.schema"),
    profitSchema:  require("./profit.schema"),
    usedCouponSchema:  require("./usedCoupon.schema"),
    usedProfitSchema:  require("./usedProfit.schema"),
}